### ISSUE TITLE
Add support for www.pbtracker.net

### ISSUE THREAD

**Issue by okiyama** [Zingler/Msplit#2]
PBTracker has an API which could allow for automatically uploading splits when they are done with MSplit. Would have to talk with the dev of PBTracker about how the API works though.

**Comment by Zingler** [comment]
Hey, Thanks for the idea. I don't think I'll be implementing this soon however. I'd like to focus on the tool itself before trying to integrate with other systems. Holding onto user credentials is also a bit of a sticky business.
